customer_order_customer_homepage:
    path:     /
    defaults: { _controller: CustomerOrderCustomerBundle:Default:index }

get_list_customers:
    path: /get/list/customers/
    defaults: { _controller:  CustomerOrderCustomerBundle:CustomerOrder:getListCustomers }

add_customer:
    path: /add/customer/
    methods: POST
    defaults: { _controller: CustomerOrderCustomerBundle:CustomerOrder:addCustomer }

get_info_customer_update:
    path: /get/info/customer/update/
    methods: POST
    defaults: { _controller: CustomerOrderCustomerBundle:CustomerOrder:getInfoCustomerUpdate }

get_list_orders:
    path: /get/list/orders/
    methods: POST
    defaults: { _controller: CustomerOrderCustomerBundle:CustomerOrder:getListOrders }

edit_customer:
    path: /edit/customer/
    methods: POST
    defaults: { _controller: CustomerOrderCustomerBundle:CustomerOrder:editCustomer }

add_order:
    path: /add/order/
    methods: POST
    defaults: { _controller: CustomerOrderCustomerBundle:CustomerOrder:addOrder }

delete_customer:
    path: /delete/customer/
    methods: POST
    defaults: { _controller: CustomerOrderCustomerBundle:CustomerOrder:deleteCustomer }

