<?php

namespace CustomerOrder\CustomerBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CustomersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomersRepository extends EntityRepository
{
    /**
     * Get id name customers
     *
     * @return \Doctrine\ORM\Query
     */
    public function getIdNameCustomers()
    {
        $query = $this->createQueryBuilder("c")
            ->select("c.customerId")
            ->addSelect("c.name");

        return $query->getQuery();
    }
}
